spring:
  application:
    name: mscartoes
  rabbitmq:
      host: ${RABBITMQ-SERVER}
      port: 5672
      username: guest
      password: guest

server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://curso-eureka-user:curso-eureka-pass@${EUREKA-SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}

mq:
  queues:
    emissao-cartoes: "emissao-cartoes"

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  charset:
    file: ./logs/log-file.log

